# Generated by Django 3.0.5 on 2020-04-25 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('invitations', models.IntegerField()),
                ('visits', models.IntegerField(default=0)),
                ('born', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='Hombre', max_length=50)),
                ('civilStatus', models.CharField(default='Soltero', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.User')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.User'),
        ),
        migrations.CreateModel(
            name='PersonalSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('video', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.User')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_assigned', to='models.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_created', to='models.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentprofile_requests_created', to='models.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentprofile_requests_assigned', to='models.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.User')),
            ],
        ),
    ]
