# Generated by Django 3.0.5 on 2020-04-25 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='date',
        ),
        migrations.AddField(
            model_name='photo',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
