# Generated by Django 3.0.5 on 2020-05-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_commentstatus_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='hasAnswers',
            field=models.CharField(default='no', max_length=10),
        ),
    ]
