# Generated by Django 3.0.5 on 2020-05-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_status_hasanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentprofile',
            old_name='hasAnswer',
            new_name='hasAnswers',
        ),
    ]
