# Generated by Django 3.0.5 on 2020-06-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20200517_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequest_requests_assigned', to='models.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendrequest_requests_created', to='models.User')),
            ],
        ),
    ]
