# Generated by Django 3.0.5 on 2020-06-10 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privatemessage_requests_assigned', to='models.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privatemessage_requests_created', to='models.User')),
            ],
        ),
    ]
