# Generated by Django 3.0.5 on 2020-06-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_auto_20200611_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='born',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
