# Generated by Django 3.0.5 on 2020-06-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20200611_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='civilStatus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invitations',
        ),
        migrations.RemoveField(
            model_name='user',
            name='visits',
        ),
    ]
