# Generated by Django 3.0.5 on 2020-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20200611_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='civilStatus',
            field=models.CharField(default='Soltero', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Hombre', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='invitations',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
