# Generated by Django 3.0.5 on 2020-06-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20200611_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='born',
        ),
    ]
