# Generated by Django 3.0.5 on 2020-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_remove_user_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='born',
            field=models.DateField(blank=True, null=True),
        ),
    ]
